wandb: cvsim
name: ffs
stage_name: ffs_sr10_bs14
vars:
  lr: 5.0e-4
  batch_size: 14
  max_batch_size: 14
  epochs: 1000
  clamp: 0
  clamp_mode: log

  optim:
    kind: adamw
    lr: ${vars.lr}
    weight_decay: 5.0
    schedule:
      template: ${yaml:schedules/wupcos_epoch}
      template.vars.end_epoch: 50

datasets:
  train:
    kind: ffs_dataset
    split: train
    num_input_points_ratio: [ 0.5, 0.8 ]
    # num_query_points_ratio: 0.1
    collators:
      - kind: ffs_collator
  test:
    kind: ffs_dataset
    split: test
    collators:
      - kind: ffs_collator

model:
  kind: ffs_model
  conditioner:
    kind: conditioners.re_conditioner
    kwargs: ${select:dim128:${yaml:models/dim}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.rans_pool_transformer_perceiver
    num_latent_tokens: ${vars.num_latent_tokens}
    enc_depth: 4
    kwargs: ${select:dim64to128:${yaml:models/encoders/pool_transformer_perceiver}}
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 4
    kwargs: ${select:dim128:${yaml:models/latent/transformer}}
    optim: ${vars.optim}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    depth: 4
    use_last_norm: true
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    kwargs: ${select:dim128to64:${yaml:models/decoders/transformer_perceiver}}
    optim: ${vars.optim}

trainer:
  kind: ffs_trainer
  precision: bfloat16
  backup_precision: float16
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 1
  callbacks:
    - kind: offline_loss_callback
      every_n_epochs: 1
      dataset_key: test
    - kind: best_checkpoint_callback
      every_n_epochs: 1
      metric_key: loss/test/total